# .github/workflows/deploy-project.yml

name: Node build

on:
  push:
    branches: [main]

jobs:
  deploy-to-sftp:
    uses: miguelms95/ci-workflow--node/.github/workflows/ci-node-deploy.yml@main
    with:
      node_version: '20'
      deploy_sftp: false